server:
  port: 8761
spring:
  application:
    name: cyber-done-discovery
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false