server:
  port: 8761
spring:
  application:
    name: cyber-done-discovery
eureka:
  instance:
    hostname: 192.168.1.100
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false